apiVersion: apps/v1
kind: Deployment

metadata:
  name: express-app
spec:
  selector:
    matchLabels:
      app: express-app

  replicas: 1

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: local/express-app:v1
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  type: ClusterIP
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-app
  labels:
    name: express-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: express-app
                port:
                  number: 80
